{
axis_angular: 0,
axis_depth: 4,
axis_linear: 1,
button_emegency_stop: 0,
button_hand_control: 1,
frequency: 10,
joy_gate: 0.14999999999999999,
scale_angular: 1.0,
scale_depth: 1.0,
scale_linear: 1.0,
server_hosts: '192.168.1.10,192.168.1.20',
server_port: 1234
}
