{
axis_angular: 3,
axis_depth: 2,
axis_linear: 1,
button_emegency_stop: 1,
button_hand_control: 2,
frequency: 3,
joy_gate: 0.001,
scale_angular: 100.0,
scale_depth: 200.0,
scale_linear: 100.0,
server_hosts: '10.13.37.33,10.13.37.34,10.13.37.50,10.13.37.30',
server_port: 1234
}
