#ifndef MODULE_SERIALPORT_GLOBAL_H
#define MODULE_SERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_SERIALPORT_LIBRARY)
#  define MODULE_SERIALPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_SERIALPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_SERIALPORT_GLOBAL_H
