#ifndef MODULE_PRESSURESENSOR_GLOBAL_H
#define MODULE_PRESSURESENSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_PRESSURESENSOR_LIBRARY)
#  define MODULE_PRESSURESENSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_PRESSURESENSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_PRESSURESENSOR_GLOBAL_H
