#ifndef MODULE_THRUSTER_GLOBAL_H
#define MODULE_THRUSTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_THRUSTER_LIBRARY)
#  define MODULE_THRUSTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_THRUSTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_THRUSTER_GLOBAL_H
