#ifndef MODULE_SCANNINGSONAR_GLOBAL_H
#define MODULE_SCANNINGSONAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_SCANNINGSONAR_LIBRARY)
#  define MODULE_SCANNINGSONARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_SCANNINGSONARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_SCANNINGSONAR_GLOBAL_H
