#ifndef MODULE_HANDCONTROL_GLOBAL_H
#define MODULE_HANDCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_HANDCONTROL_LIBRARY)
#  define MODULE_HANDCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_HANDCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_HANDCONTROL_GLOBAL_H
